eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9005/eureka
      
management:
  endpoint:
    health:
      show-details: always
      enabled: true
